[package]
name = "statistics"
version = "0.1.0"
edition = "2021"

[dependencies]
lapin = "*"
tokio = { version = "1", features = ["full"] }
futures-lite = "2.3.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
log = "0.4.21"
env_logger = "0.11.3"